# Generated by Django 4.1.5 on 2023-01-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.author')),
            ],
        ),
    ]
